include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    inference_failure_on_function_invocation: ignore
    strict_raw_type: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - 'pubspec.yaml'