name: weather_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  fpdart: ^1.1.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  weather_pack:
    git:
      url: https://github.com/dokumanx/weather_pack.git
      ref: master
  weather_animation: ^1.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  rxdart: ^0.28.0
  json_annotation: ^4.9.0
  searchfield: ^1.2.2
  flutter_animate: ^4.5.2
  dio: ^5.7.0
  responsive_builder: ^0.7.1
  device_preview_plus: ^2.2.3


dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

dependency_overrides:
  intl: any

flutter:
  uses-material-design: true
  generate: true
